In [1]:
import torch

/home/kyle/dev/makemore-and-friends/nn/.venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:279: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
torch.tensor([1])

tensor([1])

In [ ]:
import random
import torch.nn.functional as F

class Neuron:
    def __init__(self, nins: int, activation: str = "relu") -> None:
        # weights, initialized randomly
        self.w = [torch.tensor([random.random()], requires_grad=True) for _ in range(nins)]
        # bias, initialized randomly
        self.b = torch.tensor([random.random()], requires_grad=True)

        # the activation function
        self.activation = F.relu if activation == "relu" else F.tanh

    def __call__(self, data: list[torch.Tensor]) -> torch.Tensor:
        assert len(data) == len(self.w), "broken invariant"
        # activation(x1*w1 + x2*w2 + ... xn*wn + b)
        return self.activation(sum(d * w for d, w in zip(data, self.w)) + self.b)
    
    def forward(self, data: list[torch.Tensor]) -> torch.Tensor:
        return self.__call__(data)
    
    def zero_grad(self) -> None:
        assert self.b.grad is not None
        self.b.grad.zero_()

        for weight in self.w:
            assert weight.grad is not None
            weight.grad.zero_()


n = Neuron(4)
a = n([torch.tensor(1.0) for _ in range(4)])
a.backward()

for w in n.w:
    print(w.grad)

tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
